language: ruby
install: gem install jekyll html-proofer jekyll-sitemap
script: jekyll build
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
