language: ruby
before_install:
- travis_retry gem install github-pages
- travis_retry gem install jekyll
- travis_retry gem install html-proofer
script: jekyll build
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
