# Build settings

markdown: kramdown
permalink: pretty
collections:

  casestudy:
     output: true
     permalink: /casestudy/:path/
  upskilling_courses:
     output: true
     permalink: /upskilling_courses/:path/
  jobboard:

include: ["_pages"]







