# Build settings
markdown: kramdown
permalink: pretty
collections:
  casestudy:
     output: true
     permalink: /casestudy/:path/
  upskilling_cs:
     output: true
     permalink: /upskilling_cs/:path/
  jobboard:
include: ["_pages"]
prose:
  metadata:
    _posts:
      - name: "description"
        field:
          label: "Description"
          element: "textarea"
          value: "description"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "A awesome Headline!"